modLoader="javafml"
loaderVersion="[0,)"
license="Not for sale"
[[mods]]
modId="forgotteneast"
logoFile="logo.png"
version="1.0.4"
displayName="Forgotten East"
credits = "All credits reserved"
authors="Me"
description="Type your text here"
[[dependencies.forgotteneast]]
  modId="minecraft"
  mandatory=true
  versionRange="[1.21,1.22)"
  ordering="NONE"
  side="BOTH"
